In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import tensorflow as tf


In [ ]:

# Load the dataset
df = pd.read_csv('skin_tone_pallete.csv')

# Convert HEX to RGB
def hex_to_rgb(hex):
    hex = hex.lstrip('#')
    return list(int(hex[i:i+2], 16) for i in (0, 2, 4))

df['skin_tone'] = df['skin_tone'].apply(hex_to_rgb)
df['palette'] = df['palette'].apply(lambda x: [hex_to_rgb(c) for c in x.split(',')])

palettes = np.array(df['palette'].tolist())
palettes = palettes.reshape(palettes.shape[0], -1)

# Split data into train and test sets
X = np.array(df['skin_tone'].tolist())
y = palettes

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [ ]:
print(X)

[[239 199 177]
 [238 198 177]
 [239 197 177]
 ...
 [ 22   8  13]
 [ 18   7  12]
 [ 19   6  13]]


In [ ]:
# Define the model
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(3,)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(15)
])

model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               512       
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 15)                1935      
                                                                 
Total params: 68367 (267.06 KB)
Trainable params: 68367 (267.06 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
# Train the model
history = model.fit(X_train, y_train, epochs=5000, validation_split=0.2)

Output streaming akan dipotong hingga 5000 baris terakhir.
24/24 [==============================] - 0s 7ms/step - loss: 156.4622 - mae: 7.7120 - val_loss: 1826.2174 - val_mae: 32.5231
Epoch 2502/5000
24/24 [==============================] - 0s 9ms/step - loss: 127.9901 - mae: 7.0967 - val_loss: 1639.1219 - val_mae: 30.9645
Epoch 2503/5000
24/24 [==============================] - 0s 8ms/step - loss: 160.9232 - mae: 7.6215 - val_loss: 1531.9188 - val_mae: 29.8184
Epoch 2504/5000
24/24 [==============================] - 0s 8ms/step - loss: 134.1350 - mae: 7.2141 - val_loss: 1578.2230 - val_mae: 30.2515
Epoch 2505/5000
24/24 [==============================] - 0s 7ms/step - loss: 161.3302 - mae: 7.7082 - val_loss: 1696.0820 - val_mae: 30.9483
Epoch 2506/5000
24/24 [==============================] - 0s 9ms/step - loss: 154.2467 - mae: 7.6688 - val_loss: 1774.4741 - val_mae: 32.4167
Epoch 2507/5000
24/24 [==============================] - 0s 9ms/step - loss: 183.4997 - mae: 8.2616 - val_loss:

In [ ]:
new_skin_tone = "#F1C27D"
new_skin_tone_rgb = np.array([hex_to_rgb(new_skin_tone)])
predicted_palette = model.predict(new_skin_tone_rgb)

# Convert predictions to HEX
def rgb_to_hex(rgb):
    return '#%02x%02x%02x' % tuple(rgb)

predicted_palette = predicted_palette.reshape(-1, 3).astype(int)
predicted_palette_hex = [rgb_to_hex(color) for color in predicted_palette]

print("Predicted color palette:", predicted_palette_hex)

NameError: name 'np' is not defined

In [ ]:
model.save('pallete_generator.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


# New Section